# Generated by Django 2.1.3 on 2018-12-11 23:33

import davvy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('is_xml', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('collection', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=davvy.models.Resource.generate_uuid, max_length=36)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.BigIntegerField(default=0)),
                ('protected', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='davvy.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prop',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='davvy.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('user', 'parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='prop',
            unique_together={('resource', 'name')},
        ),
    ]
